apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-docker-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-docker-k8s
    spec:  # <- This was incorrectly indented in your original YAML
      containers:
        - name: spring-boot-docker-k8s
          image: spring-boot-docker-k8s:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080